import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// Firebase SDKs
import firebase from 'firebase/compat/app';
import 'firebase/compat/firestore';
import 'firebase/compat/auth';
//import "firebase/compat/analytics";
// Firebase Hooks
import { useAuthState, useSignInWithGoogle } from 'react-firebase-hooks/auth';
import { useCollectionData } from 'react-firebase-hooks/firestore';

//Firebase Configuration
firebase.initializeApp({
  apiKey: "AIzaSyB2ErOY5ca19k0KUPcaJ3lVIEiUTd2x7Nw",
  authDomain: "mic-messaging.firebaseapp.com",
  projectId: "mic-messaging",
  storageBucket: "mic-messaging.appspot.com",
  messagingSenderId: "91116938788",
  appId: "1:91116938788:web:490086a15aa47083c2dab1",
  measurementId: "G-YXJ25B2RQM"
});

const auth = firebase.auth();
const firestore = firebase.firestore();
//const analytics = firebase.analytics();

export default function Home() {
  const [user] = useAuthState(auth); // if (signed in) user is object, else user is NULL

  return (
  <div className="App">
      <header>
      </header>
      <section>
        {user ? <TEMPOUT/> : <SignIn/>}
      </section>
    </div>
    /*
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">MICMessenger</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
    */
  )
}


function SignIn() {
  const useSignInWithGoogle = () => {
    const provider = new firebase.auth.GoogleAuthProvider();
    auth.signInWithPopup(provider);
  }

  return (
    <button onClick={useSignInWithGoogle}> Sign-In With Google</button>
  );
}

function TEMPOUT() {
  return auth.currentUser && (// Check to see if a current user exists.
  <button onClick={() => auth.signOut()}> Sign-Out With Google</button>
  );
}